FULL_DATE_FORMAT = '%Y-%m-%d %H:%M:%S'
YEAR_FORMAT = '%Y'
MONTH_FORMAT = '%Y-%m'
DAY_FORMAT = '%Y-%m-%d'
HOUR_FORMAT =  '%Y-%m-%d %H'
MINUTE_FORMAT =  '%Y-%m-%d %H:%M'
SECOND_FORMAT = FULL_DATE_FORMAT

ALL_DATE_FORMATS = [
    YEAR_FORMAT,
    MONTH_FORMAT,
    DAY_FORMAT,
    HOUR_FORMAT,
    MINUTE_FORMAT,
    SECOND_FORMAT,
]
